### ISSUE TITLE
Random Boolean network generator

### ISSUE THREAD

**Issue by jgtz** [jcrozum/StableMotifs#23]
We want to be able to generate random Boolean networks (RBN). In particular, we want Kauffman NK RBNs, threshold RBNs, and canalyzing RBNs.

A new branch I created  generates Kauffman NK RBNs.

https://github.com/jcrozum/StableMotifs/tree/random_boolean_networks

**Comment by jcrozum** [comment]
This has been merged into the main branch for quite some time. I simply forgot to close the issue.
