### ISSUE TITLE
Pydot dependency

### ISSUE THREAD

**Issue by jcrozum** [jcrozum/StableMotifs#26]
I have removed the pydot dependency from the plotting tools. We can add it back if we need to (I just commented out the relevant lines and replaced them). Using pydot has some pros and cons:

pros: has a nice hierarchical layout, makes nicer pop-up plots of the STG, nice "out of the box" behavior once set up

cons: one more thing to install & version check, pydot is a bit of a pain in Windows, maybe user should specify the layout anyway, yEd or similar tools can do this

I propose we let the user specify a layout and otherwise fall back to the networkx default. Let me know what you think.

**Comment by deriteidavid** [comment]
networkx doesn't have a good hierarchical layout generator(that I'm aware of). If we want a matplotlib visualization of succession diagrams and things that are best interpreted with a hierarchical layout we need an alternative. Or we just have to put up with pydot. We can't expect every user to have and know how to use yED.

**Comment by jcrozum** [comment]
We should not be dependent on yEd, I agree. I'm just saying that realistically, people who want to make pretty things are not going to be using our library to do it, so we should make it easy for them to pull in other tools and encourage them to do so.

That's why I think we should at least have the option to pass a layout function. Then the user can pick any layout function they want, even if we've never used it and don't want to deal with integrating it (I hear sklearn has some cool hierarchy layouts, for example). 

I was wondering if the option to pass a layout function is enough on its own; then the user can pass the pydot layout function, if they have it, for a good hierarchical layout. We would suggest this in a tutorial script and other documentation.

Alternatively, we could have four options:
1. No layout
2. "Good enough" layout (maybe planar, or something -- we can discuss this) that doesn't require extra packages, aside from networkx and matplotlib
3. "Recommended" layout (pydot hierarchical)
4. Custom function passed by user

The program would fail "upwards" on this list, so if the custom function is bad, it gives a warning and tries the pydot layout. If that fails, it gives a warning and tries the matplotlib "good enough" layout, and so on. We could then pick a default from 1-3.

So I guess my question for everyone else is: do we need options 2 and 3, or is it better to only have options 1 and 4? Or is there some better approach altogether?

**Comment by jcrozum** [comment]
These changes have been merged into the main branch already.
