### ISSUE TITLE
Testing and benchmarking

### ISSUE THREAD

**Issue by jcrozum** [jcrozum/StableMotifs#3]
1. Test simple models that are easy to verify by hand
2. Test curated biological models
3. Test "tricky" models designed to fool the code
4. Benchmark ensemble random networks against PyBoolNet's methods and the Java implementation

See the StableMotifTest1.py, StableMotifTest2.py, and StableMotifTest3.py files for examples.

**Comment by deriteidavid** [comment]
Guys, I added a unit-testing script to the main folder called test_StableMotifs.py. Right now it's in a primitive state but I will gradually improve it with new tests. It's a simple, single script to run before every major commit to the code. You're also welcome to add test functions to it as you write new code.
