### ISSUE TITLE
import error in Linux (Ubuntu 18.04) - python 3.6.6

### ISSUE THREAD

**Issue by deriteidavid** [jcrozum/StableMotifs#33]
Importing the StableMotifs in any of the tests gives an import error:

`Traceback (most recent call last):
  File "run.py", line 2, in <module>
    import StableMotifs as sm
  File "/home/david/Dropbox/CEU/BOOL_MODELS/SM_Code_new/master_repo/StableMotifs/StableMotifs/__init__.py", line 5, in <module>
    from StableMotifs import Reduction
  File "/home/david/Dropbox/CEU/BOOL_MODELS/SM_Code_new/master_repo/StableMotifs/StableMotifs/Reduction.py", line 9, in <module>
    import StableMotifs.Succession as sm_succession
  File "/home/david/Dropbox/CEU/BOOL_MODELS/SM_Code_new/master_repo/StableMotifs/StableMotifs/Succession.py", line 6, in <module>
    import StableMotifs.Reduction as sm_reduction
AttributeError: module 'StableMotifs' has no attribute 'Reduction'
`
Removing the line:
`import StableMotifs.Succession as sm_succession`
from Reduciton.py seems to solve the issue. Could you please check if this is the case in your environments? I'm still trying to understand what causes this exactly.

**Comment by deriteidavid** [comment]
I will push a version where the line is commented out because Reduction does not need the Succession module anyway. Still I would like to understand why this happened.

**Comment by jgtz** [comment]
I can confirm that I do not get a similar error.

I do not know if this is related, but I have gotten a similar error when I tried to add the parent folder  of StableMotifs in site-packages of the anaconda3 environment I am using. I ended up having to add only the StableMotifs folder with the python functions in order to not get that problem.

**Comment by jcrozum** [comment]
I don't have an explanation, but I wanted to confirm that Reduction.py does not need to import Succession.py. The import was part for a function call that eventually got removed. There are no plans to add it back, so it's worth removing whether we solve this mystery or not.

**Comment by deriteidavid** [comment]
I already pushed a version where I removed that line. Doing that solved the problem for me. So I guess unless we encounter something similar in the future we can close this issue for now.

**Comment by jcrozum** [comment]
OK, I'll close it then.
