### ISSUE TITLE
Check new version of PyBoolNet

### ISSUE THREAD

**Issue by jcrozum** [jcrozum/StableMotifs#40]
PyBoolNet has had an update. Does everything still works in the latest version on all OSes? I think they've fixed the networkx issue (#12) and made some changes to how the executables are used (I'm not sure though).

**Comment by deriteidavid** [comment]
Do you mean version 2.2.8 or something later (in pip this is the latest version)

**Comment by jcrozum** [comment]
My mistake; they have not packaged the changes into a new release (yet). Their main branch has the updates though. See https://github.com/hklarner/PyBoolNet/pull/35. I guess there's nothing we need to do right now after all, other than to keep a lookout for this to get released.

**Comment by aurelien-naldi** [comment]
Indeed it should now work with newer versions of networkx.
The change for the use of executables should NOT affect pyboolnet itself, at least for now. This is only groundwork to provide a conda package, allowing to use shared executables from separate packages instead of keeping a private copy.

**Comment by jcrozum** [comment]
Okay, that's good to know. Thanks for the info! I'll close this issue.
