### ISSUE TITLE
Error when setting include_attractors_in_diagram=True in Export.networkx_succession_diagram_motif_based()

### ISSUE THREAD

**Issue by djwooten** [jcrozum/StableMotifs#46]
In my code I can run
`GR=ex.networkx_succession_diagram_reduced_network_based(ar, include_attractors_in_diagram=True)`
with no error.

But when I run
`GM=ex.networkx_succession_diagram_motif_based(ar,include_attractors_in_diagram=True)`
I get

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-eb2447767509> in <module>
----> 1 GM=ex.networkx_succession_diagram_motif_based(ar,include_attractors_in_diagram=True)

~/School/psu/tools/StableMotifs/StableMotifs/Export.py in networkx_succession_diagram_motif_based(ar, include_attractors_in_diagram)
    116             for r in a.reductions:
    117                 r_key=list(ar.succession_diagram.motif_reduction_dict.keys())[list(ar.succession_diagram.motif_reduction_dict.values()).index(r)]
--> 118                 for i,j in G_motif_based.nodes():
    119                     if r_key==j:
    120                         G_motif_based.add_edge((i,j),'A'+str(a_index))

ValueError: too many values to unpack (expected 2)```

**Comment by jcrozum** [comment]
Thanks for the report David. We'll see if we can figure it out.

Dávid, do you know why `for i,j in G_motif_based.nodes()` works on line 103 but not on line 118?

**Comment by deriteidavid** [comment]
I do I even have fix for it. I’ll push it up tomorrow. Could we maybe have
a call sometime?

**Comment by jcrozum** [comment]
Thanks Dávid.  We can meet next week. I'll send a separate email to schedule.

**Comment by deriteidavid** [comment]
@djwooten I pushed an update, please see if it works for you now.

**Comment by djwooten** [comment]
@deriteidavid Thanks, I confirmed it works.
