### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ArturoArciniega** [jcrozum/StableMotifs#62]
Hi Jordan Rozum!

I recently tried to install **StableMotifs** in a _python environment_ but I had not success.
I saw a pip version of this package however is no up to date so I uninstalled it, I'd like to install the package, how can I do it?
I also tried ```pip install -e git+https://github.com/package/name@```but it didn't work.

Thanks a lot!

**Comment by jcrozum** [comment]
Oops, setup.py wasn't included, but I've fixed it. Running
`pip install git+https://github.com/jcrozum/StableMotifs`
should work now. Let me know if you run into any further difficulty.

**Comment by ArturoArciniega** [comment]
Thanks, now is working.
Any issue I let you know!
